SELECT MEMBER_ID, MEMBER_NAME, GENDER, SUBSTRING(DATE_OF_BIRTH, 1, 10) AS DATE_OF_BIRTH FROM MEMBER_PROFILE AS M
WHERE MONTH(DATE_OF_BIRTH) = 3 AND M.TLNO IS NOT NULL AND GENDER = 'W'
ORDER BY MEMBER_ID