-- 코드를 작성해주세요
SELECT I.ID, FISH_NAME, LENGTH FROM FISH_INFO I
JOIN FISH_NAME_INFO N ON (I.FISH_TYPE = N.FISH_TYPE)
JOIN (SELECT FISH_TYPE, MAX(LENGTH) AS M_LENGTH FROM FISH_INFO
      GROUP BY FISH_TYPE) M ON (I.FISH_TYPE = M.FISH_TYPE AND I.LENGTH = M.M_LENGTH)
      ORDER BY I.ID